version: v1.0
name: Staging
agent:
  machine:
    type: f1-standard-2
    os_image: ubuntu2004
queue:
  name: Staging
  scope: project
auto_cancel:
  queued:
    when: 'true'
fail_fast:
  stop:
    when: 'true'
blocks:
  - name: Prepare
    task:
      jobs:
        - name: Deploy
          commands:
            - echo "Deploy"
  - name: Commit
    task:
      jobs:
        - name: Test
          commands:
            - echo "Test"
        - name: Monitor
          commands:
            - echo "Monitor"
promotions:
  - name: Staging (Rollback)
    pipeline_file: staging_rollback.yml
    deployment_target: Staging
    auto_promote:
      when: result = 'failed'
  - name: Production
    pipeline_file: production.yml
    deployment_target: Production
    auto_promote:
      when: result = 'passed'
